# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0002_mpesacallbacks_mpesacalls_mpesapayment'),
        ('sanitation', '0004_auto_20190928_2128'),
    ]

    operations = [
    ]
